create database basic;

use basic;


--answer 1: what is the total number of rows in all the tables 
 select COUNT(*) from customer;
 select COUNT(*) from prod_cat_info;
 select COUNT(*) from transactions;

 --answer 2 :What is the total number of transactions that have a return? --
 select COUNT(total_amt) from transactions
where total_amt LIKE '-%';

--answer 3: As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead.--

select CONVERT(DATE, DOB, 105) as DATES from customer;

select CONVERT(DATE, Tran_date, 105) from transactions;


--answer 4 What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.--
select DATEDIFF(DAY, MIN(CONVERT(DATE, Tran_date, 105)), MAX(CONVERT(DATE, Tran_date, 105))),
DATEDIFF(MONTH, MIN(CONVERT(DATE, Tran_date, 105)), MAX(CONVERT(DATE, Tran_date, 105))),  
DATEDIFF(YEAR, MIN(CONVERT(DATE, Tran_date, 105)) , MAX(CONVERT(DATE,Tran_date, 105))) from  transactions;

--answer 5: Which product category does the sub-category DIY belong to? --
select prod_cat
from prod_cat_info
where prod_subcat LIKE 'DIY'


--answer 6(1) Which channel is most frequently used for transactions? 
--data analysis 
select TOP 1
Store_type, COUNT(transaction_id) Count_
from transactions 
group by Store_type
order by COUNT(transaction_id) DESC


--answer 7(2) What is the count of Male and Female customers in the database?
select Gender, COUNT(customer_Id) AS countingcustomer
from customer
where Gender IN ('M' , 'F')
group by Gender

--answer 8(3) From which city do we have the maximum number of customers and how many? 

select top 1
city_code, COUNT(customer_Id) CUST_CNT
from customer
group by city_code
order by CUST_CNT DESC


--answer 9 (4) How many sub-categories are there under the Books category?
select COUNT(prod_subcat) AS SUBCAT
from prod_cat_info
where prod_cat = 'BOOKS'
group by prod_cat

--answer 10 (5) What is the maximum quantity of products ever ordered?
select TOP 1 Qty
from transactions
order by  Qty DESC


--answer 11 (6) What is the net total revenue generated in categories Electronics and Books?
SELECT Sum(isnull(cast(total_amt as float),0)) as AMOUNT FROM transactions
INNER JOIN prod_cat_info ON transactions.prod_cat_code = prod_cat_info.prod_sub_cat_code
WHERE prod_cat IN ('BOOKS' , 'ELECTRONICS')
 --ans 36108859.605

--answer 12(7) How many customers have >10 transactions with us, excluding returns? --
select COUNT(customer_Id) AS CUSTOMER_COUNT
from customer where customer_Id IN 
(
select cust_id
from transactions
LEFT JOIN customer ON customer_Id = cust_id
where TOTAL_AMT NOT LIKE '-%'
group by
cust_id
having 
COUNT(transaction_id) > 10
)


--answer 13(8) What is the combined revenue earned from the Electronics & Clothing categories, from Flagship stores?
select Sum(isnull(cast(total_amt as float),0)) AS AMOUNT FROM transactions
INNER JOIN prod_cat_info ON transactions.prod_cat_code = prod_cat_info.prod_sub_cat_code
where prod_cat IN ('CLOTHING','ELECTRONICS') AND Store_type = 'FLAGSHIP STORE'
--ans 76388862.79

--answer 14 (9) what is the total revenue generated from Male customers in Electronics category? Output should display total revenue by prod sub-cat
 --select prod_subcat_code FROM transactions
--LEFT JOIN customer ON Transactions.prod_subcat_code = Customer.Gender
--WHERE prod_cat_code = '3' AND Gender = 'M'
SELECT prod_subcat_code, SUM(isnull(cast(total_amt as float),0)) as REVENUE
FROM transactions
LEFT JOIN customer ON Customer.customer_Id=Transactions.prod_subcat_code
LEFT JOIN prod_cat_info ON prod_cat_info.prod_sub_cat_code =Customer.customer_Id AND prod_cat_info.prod_sub_cat_code = prod_cat_info.prod_sub_cat_code
WHERE Gender = 'M'
GROUP BY prod_subcat_code


--answer 10 What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

SELECT TOP 5 
prod_subcat, (SUM(total_amt)/(SELECT SUM(total_amt) FROM transactions))*100 AS PERCANTAGE_OF_SALES, 
(COUNT(CASE WHEN Qty< 0 THEN Qty ELSE NULL END)/SUM(Qty))*100 AS PERCENTAGE_OF_RETURN
FROM transactions
INNER JOIN prod_cat_info ON prod_cat_code  = prod_cat_code  AND prod_sub_cat_code = prod_sub_cat_code
GROUP BY prod_subcat
ORDER BY SUM(total_amt) DESC

--answer 11 For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data? --

SELECT cust_id,SUM(isnull(cast(total_amt as float),0)) AS REVENUE FROM transactions
WHERE cust_id IN 
	(SELECT customer_Id 
	 FROM customer
     WHERE DATEDIFF(YEAR,CONVERT(DATE,DOB,103),GETDATE()) BETWEEN 25 AND 35)
     AND CONVERT(DATE,tran_date,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM transactions)) 
	 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM transactions)
GROUP BY cust_id

--answer 12 Which product category has seen the max value of returns in the last 3 months of transactions?

SELECT TOP 1prod_cat, SUM(isnull(cast(total_amt as int),0)) FROM transactions T1
INNER JOIN prod_cat_info T2 ON T1.prod_cat_code = T2.prod_cat_code AND 
										T1.prod_subcat_code = T2.prod_sub_cat_code
WHERE total_amt < 0 AND 
CONVERT(date, tran_date, 103) BETWEEN DATEADD(MONTH,-3,(SELECT MAX(CONVERT(DATE,tran_date,103)) FROM transactions)) 
	 AND (SELECT MAX(CONVERT(DATE,tran_date,103)) FROM transactions)
GROUP BY prod_cat
ORDER BY 2 DESC


--answer 13 Which store-type sells the maximum products; by value of sales amount and by quantity sold?
SELECT  Store_type, SUM(isnull(cast(total_amt as varchar),0)) as TOT_SALES, SUM(Qty) TOT_QUAN
FROM transactions
GROUP BY Store_type
HAVING SUM(total_amt) >=ALL (SELECT SUM(total_amt) FROM transactions GROUP BY Store_type)
AND SUM(Qty) >=ALL (SELECT SUM(Qty) FROM transactions GROUP BY Store_type)


--answer 14 What are the categories for which average revenue is above the overall average.
SELECT prod_cat, AVG(total_amt) AS AVERAGE
FROM transactions
INNER JOIN prod_cat_info ON prod_cat_code=prod_cat_code AND prod_sub_cat_code=prod_subcat_code
GROUP BY prod_cat
HAVING AVG(total_amt)> (SELECT AVG(total_amt) FROM transactions) 


--answer 15  Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold
SELECT prod_cat, prod_subcat, AVG(total_amt) AS AVERAGE_REV, SUM(total_amt) AS REVENUE
FROM transactions
INNER JOIN prod_cat_info ON prod_cat_code=prod_cat_code AND prod_sub_cat_code=prod_subcat_code
WHERE prod_cat in 
(
SELECT TOP 5 
prod_cat
FROM transactions 
INNER JOIN prod_cat_info ON prod_cat_code= prod_cat_code AND prod_sub_cat_code = prod_subcat_code
GROUP BY prod_cat
ORDER BY SUM(Qty) DESC
)
GROUP BY prod_cat, prod_subcat 
